# file test/copy_file.yml
---
- hosts: tests
  
##  vars:
##    - dst_file_name: destinationfile

  tasks:

  - name:  _test_show_OS_family
    debug:
      msg: System {{inventory_hostname}} is {{ansible_os_family}} family

##  - set_fact: dst_file_name = destinationfile

##  - set_fact: dst_file_name = Fedora
##    when: ansible_os_family == "RedHat"

##  - set_fact: dst_file_name = Debian
##    when: ansible_os_family == "Debian"

##  - name: _test_show_dst_file_name
##    debug: 
##      msg: Distination filename is {{ dst_file_name }}


## TODO
 

  - name: _test_make_directory
    file:
      path:  ~/test
      state: directory
      mode:  '0755' 

  - name: _test_copy_file
    copy:
      src:  /tmp/sourcefile
      dest: ~/test/{{inventory_hostname}}{{ansible_os_family}}
